geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

geekshop/basketapp/urls.py
from basketapp import views as basket
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='basket'),
    path('add/<int:pk>/', basket.add, name='add'),
    path('remove/<int:pk>/', basket.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.edit, name='edit')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/basketapp/models.py
from django.conf import settings
from django.db import models
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    add_datetime = models.DateTimeField(auto_now_add=True)

    @property
    def product_cost(self):
        return self.quantity * self.product.price

    @property
    def total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        return sum(list(map(lambda x: x.quantity, _items)))

    @property
    def total_coast(self):
        _items = Basket.objects.filter(user=self.user)
        return sum(list(map(lambda x: x.product_cost, _items)))

geekshop/basketapp/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.template.loader import render_to_string
from basketapp.models import Basket
from mainapp.models import Product

@login_required
def basket(request):
    baskets_list = Basket.objects.filter(user=request.user)

    context = {
        'baskets': baskets_list
    }
    return render(request, 'basketapp/basket.html', context)

@login_required
def add(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    basket_item = Basket.objects.filter(product=product_item, user=request.user).first()

    if not basket_item:
        basket_item = Basket(product=product_item, user=request.user)
        basket_item.quantity += 1
        basket_item.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def remove(request, pk):
    basket_item = get_object_or_404(Product, pk=pk)
    basket_item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        basket_item = Basket.objects.get(pk=pk)

        if quantity < 0:
            basket_item.quantity = quantity
            basket_item.save()
        else:
            basket_item.delete()

        basket_list = Basket.objects.filter(user=request.user)

        context = {
            'baskets': basket_list
        }

        result = render_to_string('basketapp/includes/inc_baskets_list.html', context)

        return JsonResponse({'result': result})

geekshop/basketapp/templates/basketapp/includes/inc_baskets_list.html
{% for item in baskets %}
    <div class="basket_record">
      <img src="/media/{{ item.product.image }}"
           alt="{{ item.product.short_desc }}">
      <span class="category_name">{{ item.product.category.name }}</span>
      <span class="product_name">{{ item.product.name }}</span>
      <span class="product_price">{{ item.product.price }}&nbspруб</span>
      <input type="number" name="{{ item.pk }}"
                           min="0"
                           value="{{ item.quantity }}">
      <span class="product_cost">{{ item.cost }}&nbspруб</span>
      <button class="btn btn-round">
        <a href="{% url 'basket:remove' item.pk %}" class="">
          удалить
        </a>
      </button>
    </div>
  {% endfor %}

  {% if baskets %}
    <div class="basket_summary">
      В корзине {{ baskets.0.total_quantity }} товаров общей стоимостью
        {{ baskets.0.total_cost }} руб
    </div>
  {% endif %}