geekshop/authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

geekshop/basketapp/urls.py
from basketapp import views as basket
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='basket'),
    path('add/<int:pk>/', basket.add, name='add'),
    path('remove/<int:pk>/', basket.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.edit, name='edit')
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('category/<int:pk>', mainapp.products, name='category'),
    path('product/<int:pk>', mainapp.product, name='product')
]

geekshop/mainapp/models.py
from django.db import models

# Create your models (МОДЕЛЬ)here.
# Объявляем Djang-е что это класс, который нужно отобразить в БД
class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='название')
    description = models.TextField(verbose_name='описание')

# Рекомендуеся заполнять для такой модели метод str у класса
    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('-id',)
        # Кортеж с одним параметром. Нужна ОБЯЗАТЕЛЬНО запятая!!!

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=255, verbose_name='краткое описание')
    description = models.TextField(verbose_name='описание')
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/mainapp/views.py
import random
from django.shortcuts import render, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


# Create your views here.

# КОНТРОЛЛЕР
def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    return None

def get_hot_product():
    return random.sample(list(Product.objects.all()), 1)[0]

def get_same_products(hot_product):
    products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return products_list


def index(request):
    context = {
        'title': 'Главная',
        'products': Product.objects.all()[:4],
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    context = {
        'title': 'Контакты',
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/contact.html', context)


def products(request, pk=None):

    links_menu = ProductCategory.objects.all()
    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {
                'name': 'все',
                'pk': 0
            }
        else:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)
        context = {
            'links_menu': links_menu,
            'title': 'Продукты',
            'category': category_item,
            'products': products_list,
            'basket': get_basket(request.user)
        }
        return render(request, 'mainapp/products_list.html', context=context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    context = {
        'links_menu': links_menu,
        'title': 'Продукты',
        'hot_product': hot_product,
        'same_products': same_products,
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/products.html', context=context)


def product(request, pk):
    links_menu = ProductCategory.objects.all()
    context = {
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/product.html', context)

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li><a href="{% url 'products:category' 0 %}">Все</a></li>
    {% for link_item in links_menu %}
        <li><a
                href="{% url 'products:category' link_item.pk %}"
                {% if request.resolver_match.url_mame == link_item.url %} class="active" {% endif %}
        >{{ link_item.name }}</a></li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">

<li><a href="{% url 'index' %}"
       {% if request.resolver_match.url_name == 'index' %} class="active"{% endif %}>домой</a>
</li>
<li>
    <a href="{% url 'products:products' %}"
       {% if request.resolver_match.namespace == 'products' %}class="active"{% endif %}>
    продукты
    </a>
</li>

<li>
    <a href="{% url 'contact' %}"
       {% if request.resolver_match.url_name == 'contact' %}class=" {% endif %}">
    контакты
    </a>
</li>

{% if user.is_authenticated %}
<li><a href="{% url 'auth:edit' %}">{{user.first_name|default:"Пользователь"}}</a></li>
<li><a href="{% url 'auth:logout' %}">Выйти</a></li>
{% else %}
<li>
    <a href="{% url 'auth:register' %}">Регистрация</a>
    <a href="{% url 'auth:login' %}">Войти</a>
</li>
{% endif %}

</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:basket' %}" class="basket">
    {% if basket %}
        {{ basket.0.total_cost|floatformat:0 }} руб <br>
        {{ basket.0.total_quantity }} шт
    {% endif %}
</a>